# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-07 04:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DC_Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(choices=[('Zeroth Review', 'Zeroth Review'), ('First DC', 'First DC'), ('Coursework Completion', 'Coursework Completion'), ('Comprehensive Viva', 'Comprehensive Viva'), ('Second DC', 'Second DC'), ('RAC', 'RAC'), ('Thesis Submission', 'Thesis Submission'), ('Public Viva', 'Public Viva')], default='Zeroth Review', max_length=30)),
                ('remarks', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=30)),
                ('sdate', models.DateField()),
                ('cdate', models.DateField()),
                ('Completed', models.BooleanField()),
                ('Started', models.BooleanField()),
                ('regno', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Det',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('regno', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999), django.core.validators.MinValueValidator(0)])),
                ('email', models.EmailField(max_length=254)),
                ('school', models.CharField(max_length=30)),
                ('regdate', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=10)),
                ('supervisor', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('date', models.CharField(max_length=10)),
                ('author', models.CharField(max_length=1000)),
                ('regno', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999), django.core.validators.MinValueValidator(0)])),
                ('mid', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999), django.core.validators.MinValueValidator(0)])),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Su_Personal_Det',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mid', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999), django.core.validators.MinValueValidator(0)])),
                ('email', models.EmailField(max_length=254)),
                ('sex', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=30)),
                ('aoi', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999), django.core.validators.MinValueValidator(0)])),
                ('password', models.CharField(max_length=30)),
                ('dean', models.BooleanField()),
            ],
        ),
    ]
