# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-07 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dc_meeting',
            name='progress',
            field=models.CharField(choices=[('0', 'Zeroth Review'), ('1', 'First DC'), ('2', 'Coursework Completion'), ('3', 'Comprehensive Viva'), ('4', 'Second DC'), ('5', 'RAC'), ('6', 'Thesis Submission'), ('7', 'Public Viva')], default='Zeroth Review', max_length=30),
        ),
    ]
