# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-23 03:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar',
            name='regno',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='mid',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999), django.core.validators.MinValueValidator(0)]),
        ),
    ]
