# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-07 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0002_auto_20180407_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dc_meeting',
            name='progress',
            field=models.CharField(choices=[(0, 'Zeroth Review'), (1, 'First DC'), (2, 'Coursework Completion'), (3, 'Comprehensive Viva'), (4, 'Second DC'), (5, 'RAC'), (6, 'Thesis Submission'), (7, 'Public Viva')], default=0, max_length=30),
        ),
    ]
