# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-01 06:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0002_auto_20180323_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='DC_Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(choices=[(0, 'Zeroth Review'), (1, 'First DC'), (2, 'Coursework Completion'), (3, 'Comprehensive Viva'), (4, 'Second DC'), (5, 'RAC'), (6, 'Thesis Submission'), (7, 'Public Viva')], default=0, max_length=30)),
                ('remarks', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('Completed', models.BooleanField()),
                ('Started', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Det',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('regno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Research.Scholar')),
                ('email', models.EmailField(max_length=254)),
                ('school', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Research_Det',
            fields=[
                ('regno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Research.Scholar')),
            ],
        ),
        migrations.CreateModel(
            name='Su_Personal_Det',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('school', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='scholar',
            name='email',
        ),
        migrations.RemoveField(
            model_name='scholar',
            name='id',
        ),
        migrations.RemoveField(
            model_name='scholar',
            name='name',
        ),
        migrations.RemoveField(
            model_name='scholar',
            name='school',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='school',
        ),
        migrations.AlterField(
            model_name='scholar',
            name='regno',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999999999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='research_det',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Research.Supervisor'),
        ),
        migrations.AddField(
            model_name='publications',
            name='author',
            field=models.ManyToManyField(to='Research.Scholar'),
        ),
        migrations.AddField(
            model_name='publications',
            name='author1',
            field=models.ManyToManyField(to='Research.Supervisor'),
        ),
        migrations.AddField(
            model_name='dc_meeting',
            name='scholar',
            field=models.ManyToManyField(to='Research.Scholar'),
        ),
    ]
