# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-07 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0003_auto_20180407_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dc_meeting',
            name='progress',
            field=models.CharField(choices=[('A', 'Zeroth Review'), ('B', 'First DC'), ('C', 'Coursework Completion'), ('D', 'Comprehensive Viva'), ('E', 'Second DC'), ('F', 'RAC'), ('G', 'Thesis Submission'), ('H', 'Public Viva')], default='A', max_length=30),
        ),
    ]
