# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-07 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0004_auto_20180407_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dc_meeting',
            name='cdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dc_meeting',
            name='sdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
