# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-08 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0005_auto_20180407_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dc_meeting',
            name='Completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dc_meeting',
            name='Started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dc_meeting',
            name='status',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
