# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-08 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0006_auto_20180408_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='dean',
            field=models.BooleanField(default=False),
        ),
    ]
