# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-21 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0009_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='adate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
