# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-24 15:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0010_announcement_adate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999), django.core.validators.MinValueValidator(0)])),
                ('regno', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999), django.core.validators.MinValueValidator(0)])),
                ('name', models.CharField(max_length=30)),
                ('institution', models.CharField(max_length=500)),
            ],
        ),
    ]
