# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-29 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0011_dcm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='su_personal_det',
            old_name='affiliation',
            new_name='designation',
        ),
    ]
