# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-16 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0012_auto_20180429_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_det',
            name='lname',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='su_personal_det',
            name='lname',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
