# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-18 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0016_auto_20180518_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcm',
            name='mid',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='publications',
            name='mid',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='su_personal_det',
            name='mid',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='mid',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='supmess',
            name='mid',
            field=models.CharField(max_length=15),
        ),
    ]
