# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-18 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0017_auto_20180518_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_det',
            name='phno',
            field=models.CharField(max_length=11),
        ),
    ]
